#!/usr/bin/env bash
version="1.0"
name="fw-mellanox"
depends="glibc,readline,ncurses"
description="GNU/Linux fw"
source=""
groups="app.shell"
setup()
{
	cd $SOURCEDIR
	
}
build()
{
	#make
	echo "" 
}
package()
{
	mkdir -p $DESTDIR/lib/firmware
	cp -prfv /tmp/bps/files/* $DESTDIR/lib/firmware
}


